### PR TITLE
Corrected IP Addresses in banned.json

### PR DESCRIPTION
**Pull request by realdiegopoptart**

### CODE REVIEW

**Comment by realdiegopoptart** [comment]
I came and noticed there is a major error in banned.json
I wanted to help out and contribute and fix this

**Comment by Duplon** [comment]
Much needed fix +1

**Comment by realdiegopoptart** [comment]
yeah, the community needs this pull request to be merged to the main branch, thx.

**Comment by realdiegopoptart** [comment]
Reopen pull request and merge! fast!

**Pull request closed without merging**
